[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "=0.11.0-beta.2"
actix-rt = "=2.2.0"  # remove it once actix is upgraded to 0.11+
openssl-probe = { version = "0.1.4" }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
tokio = { version = "1.15.0", features = ["sync"] }
tokio-stream = "0.1.8"
futures = "0.3.19"

near-indexer = { git = "https://github.com/near/nearcore" }