app_port: 8000
database:
  host: db
  port: 5432
  username: "postgres"
  password: "password"
  db_name: "indexer_db"
indexer:
  # run configs
  sync_mode: "from_interruption"
  await_for_node_synced: "wait_for_full_sync"
  home_dir: "donotsetthisvalueitsbug"

  # init configs
  chain_id: localnet
  #  account_id: Option<String>,
  #  test_seed: Option<String>,
  num_shards: 1
  fast: false
  #  genesis: Option<String>,
  download_genesis: false
  #  download_genesis_url: Option<String>,
  download_config: false
  #  download_config_url: Option<String>,
  #  boot_nodes: Option<String>,
  #  max_gas_burnt_view: Option<Gas>,