app_port: 8000
contract_acc: "dev-20220414034725-94826614851521"
aws_settings:
  s3_endpoint: null
  s3_bucket_name: "near-lake-data-testnet"
  s3_region_name: "eu-central-1"
  start_block_height: 87486948
near_credentials:
  account_id: "battlemon.testnet"
  public_key: "ed25519:CUxcr1GDrVqNN5g8XQ4i1YMMKjkTBdHG43L1apdVcgyX"
  private_key: "ed25519:4czqC7XpYFgtyYMDSxGqPhZaAFFwkwxMgfMT5k2KTjPgfCDfU9MvgxCUoZ3cvr1SKv4F4cpFM183cMtsvNtDY8zd"
database:
  host: db
  port: 5432
  username: "postgres"
  password: "password"
  db_name: "indexer_db"