app_port: 8000
main_account: dev-1644545937395-97963882652503
database:
  host: db
  port: 5432
  username: "postgres"
  password: "password"
  db_name: "indexer_db"
indexer:
  # run configs
  sync_mode: "latest_synced"
  await_for_node_synced: "wait_for_full_sync"
  home_dir: "donotsetthisvalueitsbug"
  # init configs
  chain_id: testnet
  #  account_id: null,
  #  test_seed: null,
  num_shards: 1
  fast: false
  #  genesis: null,
  download_genesis: true
  #  download_genesis_url: null,
  download_config: true
#  download_config_url: null,
#  boot_nodes: null,
#  max_gas_burnt_view: null,